name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-ttf-dev
      
      - name: Build
        shell: bash
        env:
          CI_BUILD_FEATURES: "gfx image ttf mixer"    
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build --release
