name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cargo-vcpkg
        run: cargo install cargo-vcpkg
      - name: Install dependencies
        run: cargo vcpkg -v build
      
      - name: Install yasm (Linux)
        if: matrix.os == "ubuntu-latest"
        run: sudo apt install yasm

      - name: Install yasm (Darwin)
        if: matrix.os == "macos-latest"
        run: brew install yasm

      - name: Build
        shell: bash
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build --features "use-vcpkg" --release

      - name: Rename artifacts
        if: matrix.os != 'windows-latest'
        run: cp target/release/deno_sdl2 deno_sdl2-${{ matrix.os }}
          
      - name: Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release draft"
          draft: true
          files: |
            deno_sdl2-ubuntu-latest
            deno_sdl2-macos-latest
            target/release/deno_sdl2.exe

